# Generated by Django 4.2.21 on 2025-05-15 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=255, verbose_name="Ім'я клієнта")),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клієнта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума до оплати')),
                ('currency', models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар США'), ('EUR', 'Євро')], default='UAH', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(verbose_name='Опис платежу (для клієнта)')),
                ('company_info', models.TextField(blank=True, default='Тут буде інформація про вашу компанію.', verbose_name='Інформація про компанію')),
                ('payment_instructions', models.TextField(blank=True, default='Тут будуть інструкції щодо процесу оплати.', verbose_name='Інструкції з оплати')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/%d/', verbose_name='Файл договору (PDF)')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('expired', 'Протерміновано'), ('deactivated', 'Деактивовано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Платіжне посилання',
                'verbose_name_plural': 'Платіжні посилання',
                'ordering': ['-created_at'],
            },
        ),
    ]
