# Generated by Django 4.2.21 on 2025-05-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentlink_payment_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='duration_minutes',
            field=models.IntegerField(choices=[(30, '30 хвилин'), (60, '1 година'), (180, '3 години'), (540, '9 годин'), (900, '15 годин'), (1440, '1 день (24 години)')], default=1440, verbose_name='Термін дії посилання'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дійсне до'),
        ),
    ]
