# Generated by Django 4.2.21 on 2025-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentlink_duration_minutes_paymentlink_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='first_opened_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Вперше відкрито'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення в адмінці'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='duration_minutes',
            field=models.IntegerField(choices=[(30, '30 хвилин'), (60, '1 година'), (180, '3 години'), (540, '9 годин'), (900, '15 годин'), (1440, '1 день (24 години)'), (0, 'Без обмеження часу')], default=1440, help_text="Відлік починається з моменту першого відкриття посилання клієнтом. Оберіть 'Без обмеження часу' для безстрокового посилання.", verbose_name='Термін дії посилання (після першого відкриття)'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('new', 'Нове (не відкрито)'), ('pending', 'Відкрито (очікує оплати)'), ('paid', 'Оплачено'), ('expired', 'Протерміновано'), ('deactivated', 'Деактивовано')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
