# Generated by Django 4.2.21 on 2025-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentlink_first_opened_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='duration_minutes',
            field=models.IntegerField(choices=[(30, '30 хвилин'), (60, '1 година'), (180, '3 години'), (540, '9 годин'), (900, '15 годин'), (1440, '1 день (24 години)'), (0, 'Без обмеження часу')], default=1440, help_text="Відлік починається з моменту першого відкриття посилання клієнтом. Оберіть 'Без обмеження часу' для безстрокового посилання.", verbose_name='Термін дії посилання'),
        ),
    ]
