# Generated by Django 4.2.21 on 2025-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentlink_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='amount_uah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Розрахована сума в гривнях', max_digits=10, null=True, verbose_name='Сума в гривнях'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Курс обміну валюти в гривнях (наприклад, 1 USD = 39.5 UAH)', max_digits=10, null=True, verbose_name='Курс обміну (в гривнях)'),
        ),
    ]
