# Generated by Django 4.2.21 on 2025-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymentlink_amount_uah_paymentlink_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума до оплати (в доларах)'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='amount_uah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Автоматично розрахована сума до оплати', max_digits=10, null=True, verbose_name='Кінцева сума до оплати'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар США'), ('EUR', 'Євро')], default='UAH', max_length=3, verbose_name='Валюта оплати'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Курс обміну валюти (наприклад, 1 USD = 39.5 UAH)', max_digits=10, null=True, verbose_name='Курс обміну'),
        ),
    ]
