# Generated by Django 4.2.21 on 2025-05-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymentlink_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума в USD'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='exchange_rate_usd_to_uah',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Поточний курс обміну долара до гривні (наприклад, 39.50)', max_digits=10, null=True, verbose_name='Курс USD/UAH'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='final_amount_uah',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Автоматично розрахована сума до оплати в гривнях', max_digits=10, null=True, verbose_name='Кінцева сума до оплати в UAH'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума до оплати (в доларах)'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAH', 'Гривня'), ('USD', 'Долар США'), ('EUR', 'Євро')], default='UAH', max_length=3, null=True, verbose_name='Валюта оплати'),
        ),
    ]
