# Generated by Django 4.2.21 on 2025-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymentlink_amount_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='amount_uah',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='monobank_invoice_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, verbose_name='ID інвойсу в monobank'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='monobank_invoice_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='URL для оплати в monobank'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='payment_processed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата і час обробки платежу'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=100.00, max_digits=10, verbose_name='Сума в USD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата створення в адмінці'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='exchange_rate_usd_to_uah',
            field=models.DecimalField(decimal_places=4, default=36.6, help_text='Поточний курс обміну долара до гривні (наприклад, 39.50)', max_digits=10, verbose_name='Курс USD/UAH'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дійсне до'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('new', 'Нове (не відкрито)'), ('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('expired', 'Протерміновано'), ('deactivated', 'Деактивовано')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['status', 'created_at'], name='payment_pay_status_f671b7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['expires_at'], name='payment_pay_expires_3bd40f_idx'),
        ),
    ]
